# .gitpod.yml
image: bigdataeurope/hive:2.3.2-postgresql-metastore

tasks:
  - name: Start Hive shell
    init: |
      echo "Welcome to your Hive workspace!"
    command: |
      echo "Type 'hive' below to start the Hive shell."
